<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $products = [
            [
                'name' => 'Pumpkin Spice Muffins',
                'description' => 'Moist and flavorful muffins packed with fall spices and pumpkin puree.',
                'price' => 390,
                'user_id' => 1,
                'created_at' => '2025-09-28 23:13:50',
                'updated_at' => '2025-09-28 12:48:16',
            ],
            [
                'name' => 'Mushrooms',
                'description' => 'Fresh button mushrooms, great for cooking.',
                'price' => 526,
                'user_id' => 1,
                'created_at' => '2025-09-28 11:59:13',
                'updated_at' => '2025-09-29 02:42:33',
            ],
            [
                'name' => 'Organic Green Tea',
                'description' => 'Delicate green tea leaves for a refreshing beverage.',
                'price' => 829,
                'user_id' => 1,
                'created_at' => '2025-09-29 03:46:01',
                'updated_at' => '2025-09-29 01:42:54',
            ],
            [
                'name' => 'Cat Scratching Post with Toys',
                'description' => 'Multi-level scratching post to keep your cat entertained.',
                'price' => 927,
                'user_id' => 1,
                'created_at' => '2025-09-28 18:31:17',
                'updated_at' => '2025-09-28 09:14:10',
            ],
            [
                'name' => 'Almond Joy Bars',
                'description' => 'Chocolate-covered candy bars with coconut and almonds.',
                'price' => 998,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:49:14',
                'updated_at' => '2025-09-28 18:37:02',
            ],
            [
                'name' => 'Scented Soy Candles',
                'description' => 'Hand-poured candles made of natural soy wax.',
                'price' => 799,
                'user_id' => 1,
                'created_at' => '2025-09-28 09:22:25',
                'updated_at' => '2025-09-29 22:00:28',
            ],
            [
                'name' => 'Stainless Steel Mixing Bowls',
                'description' => 'Set of versatile mixing bowls for cooking.',
                'price' => 300,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:06:53',
                'updated_at' => '2025-09-28 16:14:54',
            ],
            [
                'name' => 'Cajun Seasoning',
                'description' => 'Spicy seasoning mix for all your favorite dishes.',
                'price' => 651,
                'user_id' => 1,
                'created_at' => '2025-09-28 04:07:32',
                'updated_at' => '2025-09-28 11:23:46',
            ],
            [
                'name' => 'Beef Stew Meat',
                'description' => 'Tender beef chunks for slow-cooked stews.',
                'price' => 777,
                'user_id' => 1,
                'created_at' => '2025-09-28 00:28:31',
                'updated_at' => '2025-09-29 10:48:48',
            ],
            [
                'name' => 'Portable Hammock Swing',
                'description' => 'Lightweight and portable swing hammock for relaxing outdoors.',
                'price' => 399,
                'user_id' => 1,
                'created_at' => '2025-09-29 21:36:59',
                'updated_at' => '2025-09-29 07:32:12',
            ],
            [
                'name' => 'Wall Art Stickers',
                'description' => 'Removable wall art stickers for home decoration.',
                'price' => 540,
                'user_id' => 1,
                'created_at' => '2025-09-29 16:49:41',
                'updated_at' => '2025-09-29 22:35:20',
            ],
            [
                'name' => 'Graphic Tee',
                'description' => 'Soft cotton graphic tee available in various designs.',
                'price' => 357,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:49:12',
                'updated_at' => '2025-09-29 23:40:40',
            ],
            [
                'name' => 'Mint Chocolate Chip Ice Cream',
                'description' => 'Creamy ice cream with refreshing mint flavor and chocolate chips.',
                'price' => 545,
                'user_id' => 1,
                'created_at' => '2025-09-29 13:59:33',
                'updated_at' => '2025-09-29 05:13:46',
            ],
            [
                'name' => 'Utility Cargo Pants',
                'description' => 'Practical cargo pants with lots of pockets for functionality.',
                'price' => 530,
                'user_id' => 1,
                'created_at' => '2025-09-29 03:11:51',
                'updated_at' => '2025-09-28 06:37:45',
            ],
            [
                'name' => 'Bluetooth Sleep Headphones',
                'description' => 'Comfortable wireless headphones designed for sleeping.',
                'price' => 385,
                'user_id' => 1,
                'created_at' => '2025-09-29 06:05:57',
                'updated_at' => '2025-09-29 12:02:15',
            ],
            [
                'name' => 'Scent Diffuser',
                'description' => 'Ultrasonic essential oil diffuser with LED lights.',
                'price' => 747,
                'user_id' => 1,
                'created_at' => '2025-09-28 16:20:22',
                'updated_at' => '2025-09-29 07:37:04',
            ],
            [
                'name' => 'Bike Repair Tool Kit',
                'description' => 'Essential tools for bike maintenance and repair.',
                'price' => 916,
                'user_id' => 1,
                'created_at' => '2025-09-28 07:47:02',
                'updated_at' => '2025-09-28 09:14:27',
            ],
            [
                'name' => 'Chocolate Peanut Butter Cups',
                'description' => 'Delicious dark chocolate cups filled with creamy peanut butter.',
                'price' => 642,
                'user_id' => 1,
                'created_at' => '2025-09-28 11:22:18',
                'updated_at' => '2025-09-28 23:23:33',
            ],
            [
                'name' => 'Essential Oil Diffuser',
                'description' => 'Ultrasonic diffuser that helps create a calming atmosphere.',
                'price' => 396,
                'user_id' => 1,
                'created_at' => '2025-09-28 21:33:49',
                'updated_at' => '2025-09-29 06:49:52',
            ],
            [
                'name' => 'Couscous',
                'description' => 'Quick-cooking couscous, great as a side or base.',
                'price' => 959,
                'user_id' => 1,
                'created_at' => '2025-09-28 21:46:20',
                'updated_at' => '2025-09-28 18:35:12',
            ],
            [
                'name' => 'Window Bird Feeder',
                'description' => 'Suction cup bird feeder for close-up bird watching.',
                'price' => 327,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:31:58',
                'updated_at' => '2025-09-28 01:45:15',
            ],
            [
                'name' => 'Interactive Robot Toy',
                'description' => 'Fun robot that engages kids with games and activities.',
                'price' => 841,
                'user_id' => 1,
                'created_at' => '2025-09-29 23:42:18',
                'updated_at' => '2025-09-28 07:16:42',
            ],
            [
                'name' => 'Watercolor Brush Pens',
                'description' => 'Set of brush pens for colorful and creative painting.',
                'price' => 913,
                'user_id' => 1,
                'created_at' => '2025-09-29 10:53:50',
                'updated_at' => '2025-09-28 00:00:28',
            ],
            [
                'name' => 'Poppy Seed Dressing',
                'description' => 'A light and tangy dressing with poppy seeds, perfect for salads.',
                'price' => 771,
                'user_id' => 1,
                'created_at' => '2025-09-28 21:51:01',
                'updated_at' => '2025-09-29 20:46:50',
            ],
            [
                'name' => 'Chipotle Black Bean Salad',
                'description' => 'A zesty salad with black beans, corn, and chipotle dressing.',
                'price' => 180,
                'user_id' => 1,
                'created_at' => '2025-09-28 21:02:10',
                'updated_at' => '2025-09-29 08:34:17',
            ],
            [
                'name' => 'Safety Pin Dispenser',
                'description' => 'Handy dispenser for quick access to safety pins.',
                'price' => 704,
                'user_id' => 1,
                'created_at' => '2025-09-29 10:05:17',
                'updated_at' => '2025-09-29 07:14:02',
            ],
            [
                'name' => 'Non-Slip Yoga Socks',
                'description' => 'Yoga socks designed to provide better grip and stability.',
                'price' => 731,
                'user_id' => 1,
                'created_at' => '2025-09-29 11:44:17',
                'updated_at' => '2025-09-29 10:05:27',
            ],
            [
                'name' => 'Multi-Purpose Marine Rope',
                'description' => 'Heavy-duty rope suitable for boating, camping, and general use.',
                'price' => 966,
                'user_id' => 1,
                'created_at' => '2025-09-28 09:35:13',
                'updated_at' => '2025-09-29 10:44:05',
            ],
            [
                'name' => 'Miso Dressing',
                'description' => 'Flavorful dressing made with miso paste',
                'price' => 340,
                'user_id' => 1,
                'created_at' => '2025-09-28 18:44:48',
                'updated_at' => '2025-09-29 23:34:37',
            ],
            [
                'name' => 'Brown Sugar',
                'description' => 'Raw brown sugar, perfect for baking or sweetening drinks.',
                'price' => 868,
                'user_id' => 1,
                'created_at' => '2025-09-29 01:58:11',
                'updated_at' => '2025-09-29 14:59:45',
            ],
            [
                'name' => 'Fridge Magnet Set',
                'description' => 'Fun fridge magnets to decorate your kitchen.',
                'price' => 930,
                'user_id' => 1,
                'created_at' => '2025-09-29 01:20:18',
                'updated_at' => '2025-09-29 22:45:09',
            ],
            [
                'name' => 'Chickpea Flour',
                'description' => 'Gluten-free flour made from ground chickpeas, great for cooking.',
                'price' => 342,
                'user_id' => 1,
                'created_at' => '2025-09-28 08:17:32',
                'updated_at' => '2025-09-28 23:23:48',
            ],
            [
                'name' => 'Spinach and Cheese Stuffed Shells',
                'description' => 'Delicious pasta shells filled with spinach and cheese',
                'price' => 762,
                'user_id' => 1,
                'created_at' => '2025-09-28 20:10:13',
                'updated_at' => '2025-09-29 10:59:47',
            ],
            [
                'name' => 'Lemon Herb Quinoa',
                'description' => 'Fluffy quinoa mixed with lemon zest and herbs, a perfect side.',
                'price' => 776,
                'user_id' => 1,
                'created_at' => '2025-09-28 14:58:39',
                'updated_at' => '2025-09-28 01:31:58',
            ],
            [
                'name' => 'Bamboo Utensil Set',
                'description' => 'Sustainable bamboo utensils for cooking and serving.',
                'price' => 705,
                'user_id' => 1,
                'created_at' => '2025-09-28 16:49:22',
                'updated_at' => '2025-09-28 16:43:45',
            ],
            [
                'name' => 'Honey Glazed Carrots',
                'description' => 'Sweet and savory carrots glazed in honey, perfect as a side dish.',
                'price' => 175,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:38:29',
                'updated_at' => '2025-09-29 04:38:01',
            ],
            [
                'name' => 'Digital Stopwatch Timer',
                'description' => 'Accurate stopwatch for timing events and workouts.',
                'price' => 603,
                'user_id' => 1,
                'created_at' => '2025-09-29 23:50:22',
                'updated_at' => '2025-09-28 16:27:42',
            ],
            [
                'name' => 'Self-Stirring Mug',
                'description' => 'Automated stirring for your drinks with just a press of a button.',
                'price' => 437,
                'user_id' => 1,
                'created_at' => '2025-09-28 01:16:43',
                'updated_at' => '2025-09-28 03:51:23',
            ],
            [
                'name' => 'Solar String Lights',
                'description' => 'Eco-friendly string lights for outdoor decor.',
                'price' => 575,
                'user_id' => 1,
                'created_at' => '2025-09-29 11:41:06',
                'updated_at' => '2025-09-28 19:04:55',
            ],
            [
                'name' => 'Foldable Yoga Mat Carry Bag',
                'description' => 'Durable bag for carrying your yoga mat and accessories.',
                'price' => 776,
                'user_id' => 1,
                'created_at' => '2025-09-29 02:44:28',
                'updated_at' => '2025-09-28 08:41:09',
            ],
            [
                'name' => 'Children\'s Educational Puzzle',
                'description' => 'Fun and educational puzzle set for kids.',
                'price' => 904,
                'user_id' => 1,
                'created_at' => '2025-09-28 02:49:59',
                'updated_at' => '2025-09-28 22:48:57',
            ],
            [
                'name' => 'Adjustable Window Blind',
                'description' => 'Customizable window cover for light control and privacy.',
                'price' => 915,
                'user_id' => 1,
                'created_at' => '2025-09-28 05:09:29',
                'updated_at' => '2025-09-29 04:30:05',
            ],
            [
                'name' => 'Magnetic Spice Jars',
                'description' => 'Convenient magnetic jars for easy spice storage.',
                'price' => 112,
                'user_id' => 1,
                'created_at' => '2025-09-29 15:59:40',
                'updated_at' => '2025-09-28 01:59:16',
            ],
            [
                'name' => 'Non-Stick Crepe Pan',
                'description' => 'Perfectly designed pan for making crepes and pancakes.',
                'price' => 481,
                'user_id' => 1,
                'created_at' => '2025-09-28 01:36:58',
                'updated_at' => '2025-09-29 22:22:21',
            ],
            [
                'name' => 'Chickpea Pancakes',
                'description' => 'Savory pancakes made with chickpea flour, high in protein.',
                'price' => 720,
                'user_id' => 1,
                'created_at' => '2025-09-28 07:21:11',
                'updated_at' => '2025-09-28 18:05:21',
            ],
            [
                'name' => 'Chocolate Chip Cliff Bars',
                'description' => 'Nutritious energy bars packed with chocolate chips.',
                'price' => 636,
                'user_id' => 1,
                'created_at' => '2025-09-29 04:12:45',
                'updated_at' => '2025-09-28 08:23:40',
            ],
            [
                'name' => 'Vegetable and Cheese Quesadillas',
                'description' => 'Flour tortilla filled with cheese and a medley of vegetables.',
                'price' => 746,
                'user_id' => 1,
                'created_at' => '2025-09-29 05:31:09',
                'updated_at' => '2025-09-28 22:08:52',
            ],
            [
                'name' => 'Mashed Sweet Potatoes',
                'description' => 'Creamy mashed sweet potatoes with a hint of cinnamon.',
                'price' => 194,
                'user_id' => 1,
                'created_at' => '2025-09-29 16:10:53',
                'updated_at' => '2025-09-28 17:09:44',
            ],
            [
                'name' => 'Rechargeable Hand Warmer',
                'description' => 'Portable rechargeable warmer for cold days.',
                'price' => 764,
                'user_id' => 1,
                'created_at' => '2025-09-29 17:11:15',
                'updated_at' => '2025-09-29 20:50:25',
            ],
            [
                'name' => 'Red Lentil Pasta',
                'description' => 'Gluten-free pasta made from red lentils, packed with protein.',
                'price' => 541,
                'user_id' => 1,
                'created_at' => '2025-09-28 13:21:09',
                'updated_at' => '2025-09-28 19:57:37',
            ],
        ];
        //
        DB::table('products')->insert($products);
    }
}
